namespace RPGDemo.Controllers;

// Don't change the order else change characterEditorForm and the project file
public enum AnimationIndex
{
    IdleRight,
    IdleLeft,
    IdleUp,
    IdleDown,
    IdleUpRight,
    IdleDownRight,
    IdleUpLeft,
    IdleDownLeft,

    WalkRight,
    WalkLeft,
    WalkUp,
    WalkDown,
    WalkUpRight,
    WalkDownRight,
    WalkUpLeft,
    WalkDownLeft,

    AttackRight,
    AttackLeft,
    AttackUp,
    AttackDown,
    AttackUpRight,
    AttackDownRight,
    AttackUpLeft,
    AttackDownLeft,

    Attack2Right,
    Attack2Left,
    Attack2Up,
    Attack2Down,
    Attack2UpRight,
    Attack2DownRight,
    Attack2UpLeft,
    Attack2DownLeft,

    Attack3Right,
    Attack3Left,
    Attack3Up,
    Attack3Down,
    Attack3UpRight,
    Attack3DownRight,
    Attack3UpLeft,
    Attack3DownLeft,

    HitRight,
    HitLeft,
    HitUp,
    HitDown,
    HitUpRight,
    HitDownRight,
    HitUpLeft,
    HitDownLeft,

    Magic1Right,
    Magic1Left,
    Magic1Up,
    Magic1Down,
    Magic1UpRight,
    Magic1DownRight,
    Magic1UpLeft,
    Magic1DownLeft,

    Magic2Right,
    Magic2Left,
    Magic2Up,
    Magic2Down,
    Magic2UpRight,
    Magic2DownRight,
    Magic2UpLeft,
    Magic2DownLeft,

    DyingRight,
    DyingLeft,
    DyingUp,
    DyingDown,
    DyingUpRight,
    DyingDownRight,
    DyingUpLeft,
    DyingDownLeft,

    DeadRight,
    DeadLeft,
    DeadUp,
    DeadDown,
    DeadUpRight,
    DeadDownRight,
    DeadUpLeft,
    DeadDownLeft,

    ToRageStateRight,
    ToRageStateLeft,
    ToRageStateUp,
    ToRageStateDown,
    ToRageStateUpRight,
    ToRageStateDownRight,
    ToRageStateUpLeft,
    ToRageStateDownLeft,

    ToNormalStateRight,
    ToNormalStateLeft,
    ToNormalStateUp,
    ToNormalStateDown,
    ToNormalStateUpRight,
    ToNormalStateDownRight,
    ToNormalStateUpLeft,
    ToNormalStateDownLeft,
}