<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNetter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CasaEngine\CasaEngine.csproj" />
    <ProjectReference Include="..\MGUI\MGUI.Core\MGUI.Core.csproj" />
    <ProjectReference Include="..\MGUI\MGUI.Shared\MGUI.Shared.csproj" />
  </ItemGroup>
</Project>