#region Using Directives

using System;
using System.Collections.Generic;

#endregion

namespace CasaEngine.AI.EvolutionaryComputing.Crossover
{
	/// <summary>
	/// Delegate that represents a crossover method
	/// </summary>
	/// <typeparam name="T">The type of the genes</typeparam>
	/// <param name="parents">The parents to cross</param>
	/// <returns>The childs generated by the crossover</returns>
	public delegate List<Chromosome<T>> CrossoverMethod<T>(List<Chromosome<T>> parents);
}
