namespace CasaEngine.AI.EvolutionaryComputing
{
	/// <summary>
	/// Delegate used to give information about new populations generated by 
	/// the evolutionary algorithm
	/// </summary>
	/// <typeparam name="T">Type of the genes</typeparam>
	/// <param name="population">New population generated</param>
	public delegate void NewStepEventHandler<T>(Population<T> population);
}
