<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(WindowsTargetFramework)</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>
		<OutputType>Library</OutputType>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FontStashSharp.MonoGame" />
		<PackageReference Include="MonoGame.Framework.DesktopGL" />
	</ItemGroup>
</Project>