#region Using Directives

using System;
using System.Collections.Generic;

using CasaEngine.AI.Navigation;

#endregion

namespace CasaEngine.AI.Pathfinding
{
	/// <summary>
	/// This delegate represents a path smothing algorithm that tires to optimize
	/// the path generated by a pathfinding algorithm
	/// </summary>
	/// <param name="entity">The entity that´s going to move through the path</param>
	/// <param name="path">The path the algorithm is going to try to smooth</param>
	public delegate void PathSmoother(MovingEntity entity, List<NavigationEdge> path);
}
