#region Using Directives

using System;

#endregion

namespace CasaEngine.AI.EvolutionaryComputing.Replacement
{
	/// <summary>
	/// Delegate that represents a replacement method
	/// </summary>
	/// <typeparam name="T">The type of the genes</typeparam>
	/// <param name="parents">The parents population</param>
	/// <param name="children">The children population</param>
	/// <returns>The new population generated by the replacement</returns>
	public delegate Population<T> ReplacementMethod<T>(Population<T> parents, Population<T> children);
}
